#ifndef ERRORS_H
#define ERRORS_H

enum return_code
{
    RC_OK,
    RC_UNDEFINED_ACTION,
    RC_FILE_OPEN_ERROR,
    RC_FILE_READ_ERROR,
    RC_FILE_WRITE_ERROR,
    RC_MEMORY_ALLOCATION_ERROR,
    RC_FIGURE_NOT_LOADED,
    RC_INCORRECT_POINTS,
    RC_INCORRECT_EDGE,
    RC_INCORRECT_EDGES,
    RC_INCORRECT_FIGURE,
    RC_POINTS_SIZE_ERROR,
    RC_EDGES_SIZE_ERROR,
    RC_SCALE_COEFF_ERROR,
    RC_INCORRECT_SCENE
};
using rc_t = enum return_code;

#endif
